spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bulls?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        # 만들어진 sql 보여주기
#        show_sql: true
        # sql 가독성 좋게 보여줌
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret_key: 015a0705cca373d659869c9f707c5c583fd313c01171c9633999edb9169361c4d7fcf7bb23dced5669b0f4aaee8f3e96a5d15d81a547d6dfd23a6dad8594ff56
  # AccessToken 만료시간
  # 밀리초 단위 1800000 = 30분
  expiration_access: 3000
  # refreshToken 만료시간
  expiration_refresh: 86400000
  issuer: Bulls

